#!/usr/bin/env bash
#
# User specific aliases and functions
#

# ls Aliases

if command ls --help 2>&1 | grep -q -- --color; then
	alias ls='\ls --color=auto -F'
else
	alias ls='\ls -CFG'
fi

alias la='ls -a'
alias ll='ls -l'
alias lat='ls -lat'
alias latr='ls -latr'
alias lathr='ls -lathr'

# MISC Aliases

# shellcheck disable=SC2154
alias where='for ix in ${!DIRSTACK[@]}; do echo ${DIRSTACK[$ix]}; done'

alias dps="docker ps --format '{{ printf \"%-30s %-20s %s\" .Names .Status .Ports }}'"
alias emacs='emacs -nw'
alias k='kubectl'
alias python='python3'
alias tf='terraform'
alias tmux='tmux -2u'
