set -g default-terminal "screen-256color"

setw -g automatic-rename on
set-option -g automatic-rename-format '#{=/15/...:#{b:pane_current_path}}'
set -g renumber-windows on
set -g status-interval 5

set -g monitor-activity on
set -g visual-activity off

set -g status-style bg=default
set -g status-style fg=default
set -ag terminal-overrides ",*:XT@"

set -s escape-time 10
set -sg repeat-time 600
set -g history-limit 5000

if '[ -f ~/.local.tmux.conf ]' 'source ~/.local.tmux.conf'
