#!/usr/bin/env bash

if [ -f "${HOME}/.profile" ]; then
  # shellcheck disable=SC1090
  . "${HOME}/.profile"
fi

if [ -n "${BASH_VERSION}" ]; then
  if [ -f "${HOME}/.bashrc" ]; then
    # shellcheck disable=SC1090
    . "${HOME}/.bashrc"
  fi
fi

